CenterForOpenScience/scrapi

- scrapi/base/__init__.py
- scrapi/linter/__init__.py
- scrapi/linter/document.py
- scrapi/linter/util.py
Linting now should reject missing URLs! Modified base classes to accept more customized base urls, and added optional time between requests for providers of different sensitivities. Also allowed for properties to be pulled from the OAI header as well as from within the dc elements.
> Fix linting, modify base OAI harvester

- scrapi/consumers/mit/__init__.py
Many entires have more than one description field, add list of descriptions to the properties so none are missed.
> Add other descriptions to MIT properties

- scrapi/consumers/doepages/consumer.py
doepages had an extra 'raw' field in the normalized document that was a string of the whole raw xml record (probably left over from when we were experimenting with that...)
If a migration is run, we should remove those, maybe?
> remove raw docstring of xml from doepages normalized record

- scrapi/consumers/figshare/consumer.py
Figshare was not saving date_published, most likely because I removed it and forgot to move it to properties. when we decided to only show dateUpdated in the main schema. Date published is now saved to properties.
> Add logging, and date published to properties

- scrapi/base/__init__.py
Blank titles are now set to empty string, and deleted records are not normalized (as they do not contain any information except for the service ID). Also, rejected sets are now only logged after all setSpecs in the header have been checked.
> Update base harvester

- scrapi/harvesters/figshare.py
Resolves Centerforopenscience/osf.io#2329
> Link figshare results to DOI instead of URL to more metadata

- .travis.yml
- scrapi/util.py
- scripts/delete.py
- scripts/rename.py
- tasks.py
- Run provider map in tests.
- Ignore unicode-decode errors in copy_to_unicode
- Don't delete documents from cassandra (yet), do delete them from all elasticsearch indices.
- Delete old provider map before making a new one
- Add delete task
> More 0.6 fixes

- scrapi/base/__init__.py
- scrapi/events.py
- scrapi/harvesters/biomedcentral.py
- scrapi/harvesters/clinicaltrials.py
- scrapi/harvesters/crossref.py
- scrapi/harvesters/dataone.py
- scrapi/harvesters/doepages.py
- scrapi/harvesters/figshare.py
- scrapi/harvesters/osf.py
- scrapi/harvesters/plos.py
- scrapi/harvesters/scitech.py
- scrapi/harvesters/stepic.py
- scrapi/settings/defaults.py
- scrapi/tasks.py
- scrapi/util.py
- tasks.py
- tests/test_harvesters.py
- tests/test_logging.py
- tests/test_oai_harvester.py
- tests/test_processing.py
- tests/test_tasks.py
Remove the "days_back" argument from harvesters and instead use a date range. Defaults to harvesting from the day before to the current day.
> Add date range to all harvesters 

- scrapi/harvesters/shareok.py
Add a list of approves sets to harvest, that do not include undergrad research. 
ES mapping was failing for occasionally malformed dates in otherProperties - will add back in once we fix this.
> Add approved Sets to SHAREOK, remove date from otherProperties for now

- scrapi/harvesters/osf.py
Harvests will now automatically happen for a 2 day period starting 4 days in the past, to honor the 48 hours promised to contributors to public projects to make the registration private.
> [hotfix] Update OSF harvester to honor period given to retract public registrations

- scrapi/harvesters/dailyssrn.py
Will require a reboot of the production box, + ```inv provider_map -d``` to remove the old name and replace it with this one.
> fix name for daily ssrn

- scrapi/base/helpers.py
- tests/test_helpers.py
For OAI harvesters - a ValueError will be raised if no URI is returned for a particular record
> Add raising a value error if no uri was returned for cannonical uri

- scrapi/harvesters/cyberleninka.py
- scrapi/harvesters/dash.py
- scrapi/harvesters/datacite.py
- scrapi/harvesters/digitalhoward.py
- scrapi/harvesters/dryad.py
- scrapi/harvesters/hacettepe.py
- scrapi/harvesters/icpsr.py
- scrapi/harvesters/iowaresearch.py
- scrapi/harvesters/mblwhoilibrary.py
- scrapi/harvesters/scholarworks_umass.py
- scrapi/harvesters/smithsonian.py
- scrapi/harvesters/wustlopenscholarship.py
The Auto-OAI harvest creator was not saving correct urls that are saved to the provider map - instead, was using the base OAI urls that usually don't direct anywhere useful.
This PR updates those that I found to be actual home pages for sources.
One line in a bunch of different harvesters.  This really should only affect the SHARE OSF search page - clicking on the sources in each search result - along with the SHARE registration page that has the sources listed.
> Update many OAI URLs to point to real source pages

- scrapi/harvesters/datacite.py
Previously, datacite was saving a list in the cannnonical URI field, instead of a single element.  This makes the result a single string, no matter what!
> Update datacite Cannonical uri harvesting

- scrapi/linter/document.py
noticed this popping up for some harvesters, now use .get instead of direct access in repr for normalized document
> Fix errors in repr when serializing for fluentd

- scrapi/harvesters/clinicaltrials.py
This fixes two small typos in the clinicaltrials.gov harvester.  The typo in the url does not currently seem to cause any problems.  The typo in the xpath expression will cause the eligibility key to always be empty.
Cheers,
Fitz
> fix typos in clinicaltrials.gov harvester

- scrapi/harvesters/pubmedcentral.py
- tests/vcr/pubmedcentral.yaml
The original pubmedcentral OAI-PMH url:
http://www.pubmedcentral.nih.gov/oai/oai.cgi
...now returns a permanent redirect to a new url base:
http://www.ncbi.nlm.nih.gov/pmc/oai/oai.cgi
This commit updates the harvester and the tests with the new url.  The
tests were updated with a search-and-replace. All pass without further
modification.
> [feature] update pubmedcentral OAI-PMH endpoint

- .gitignore
- scrapi/base/helpers.py
- scrapi/harvesters/dataone.py
- tests/test_helpers.py
Closes [#SHARE-54]
A harvester with a long piece of text was incorrectly parsing the URL to include a "]" at the end.
This PR fixes that, and also generally improves URL parsing to also search for dois inside of paragraphs of text.
> Update URI Processing

- api/webview/migrations/0002_auto_20151113_1515.py
- api/webview/migrations/0003_version_status.py
- api/webview/models.py
- scrapi/linter/document.py
- scrapi/migrations.py
- scrapi/processing/base.py
- scrapi/processing/cassandra.py
- scrapi/processing/postgres.py
- scrapi/processing/storage.py
- scrapi/tasks.py
- tests/test_migrations.py
+ Postgres versioning
+ Migration to/from cassandra
[#SHARE-166]
> [Ready for Review] Postgres updates

- README.md
- tasks.py
Update docs and path to point to the new files, and giving better directions to getting ipeds information.
> Update to latest grids and ipeds files

- README.md
SPRINGER_KEY should be SPRINGER_API_KEY to match variable name in springer.py
> Update README: SPRINGER_KEY changed to SPRINGER_API_KEY

- scrapi/harvesters/push_api.py
Somehow contributors with email='' got through. This is a quick fix to fix normalization on these.
> Push API Validation 

- scrapi/harvesters/crossref.py
Move tags is located from "other properties" to "subjects' in the schema
> add subjects for crossref

- api/webview/views.py
- tests/test_api_views.py
I changed the webview DocumentList view to exclude non-normalized documents from being displayed.
I wrote a test case in test_api_views in order to confirm that non-normalized documents are not being displayed.
I ran the test case and I believe the alterations are working.
> Created filter so non-normalized documents are no longer displayed with test case

- tasks.py
Django env variable is overwritten in the OSF and causes local scrapi errors when running scrapi and the OSF one after another... might be a better way to fix this, but this seems to be how the OSF sets the variable.
> Fix django settings import conflict with OSF
