CenterForOpenScience/scrapi

scrapi/base/__init__.py
Make harvester class an abstract base class, change days back keyword arg
=> Harvester class changes

scrapi/linter/util.py
=> Put parenthesis in the right place

.travis.yml, requirements.txt, scrapi/processing/elastic_search.py, scrapi/settings/local-dist.py, scrapi/settings/travis-dist.py, tests/test_elasticsearch_processor.py, tests/utils.py
@chrisseto @jeffspies @erinspace 
Elasticsearch backend for scrapi. Filters data based on the FRONTEND_KEYS setting, so that the data we expose to to the users is easily configurable.
=> Elasticsearch processor for scrapi

scrapi/consumers/dataone/consumer.py
Allows for trailing slash and extra numbers in DOIs that can still be resolved
=> Update how DOIs are harvested from dataone

scrapi/consumers/trinity/__init__.py
These were totally wrong, as they were copied from the texasstate harvester and never updated!.
=> Update trinity OAI url and variable names

scrapi/consumers/valposcholar/__init__.py
To be more inclusive of the data they  provide.
=> Update valposcholar properties

scrapi/consumers/scitech/consumer.py
Rearranges properties and add rights, type, and date added
=> Make scitech properties more complete and uniform

scrapi/base/helpers.py
fixes CenterForOpenScience/osf.io#2278, upgrades #119 to a hotfix
=> Add regex to url finder helper method, upgraded to hotfix

scrapi/harvesters/plos.py
=> Move plos to new harvester system

scrapi/base/schemas.py, scrapi/base/transformer.py, scrapi/harvesters/plos.py, tests/test_transformer.py
=> Add constants and functions to the transformer language

requirements.txt, scrapi/base/transformer.py, scrapi/harvesters/biomed.py, scrapi/harvesters/crossref.py, scrapi/harvesters/figshare.py, tests/test_json_harvester.py
String processing for JSON now uses RFC6901
=> JSON Nested syntax

README.md
Added Cassandra and ElasticSearch installation instructions for Ubuntu users.
=> Install Cassandra and ElasticSearch on Ubuntu

scrapi/processing/storage.py, tests/test_storage.py
Code actually from Fabian.
https://gist.github.com/fabianvf/597f57ffe8351156bb98
=> Add back flat file storage for testing and development

scrapi/harvesters/pubmed.py
Pubmed URIs all went to the same place, this adds a custom URI parser that finds the right url.
Add new uri parser using existing helper function
Should only effect pubmed, old records will need to be renormalized!
=> Add custom OAI schema for pubmed uris

scrapi/base/schemas.py
=> add tags back to oai base schema

scrapi/harvesters/stepic.py, scrapi/requests.py
=> Make it so that stepic can save non-200 results

scrapi/events.py, scrapi/processing/__init__.py
=> send errors in the processing module to sentry

requirements.txt, scrapi/database.py, scrapi/processing/cassandra.py, scrapi/requests.py, scripts/util.py
@chrisseto @erinspace should be good to go.
=> Move to the new python driver for cassandra

scripts/util.py
=> Fix broken import

tests/test_base.py
Work still in progress. Python3: all tests passed, Python2: 2 tests failed.
=> Fix pytest exception asserts

scrapi/tasks.py
Add retries to task decorators to retry celery tasks in case they fail the first time.  A very basic form of error handling, but seems to cut down on failures at least locally.
@chrisseto
=> Add retries to task decorators to minimize failed tasks

tasks.py
Removed server method from tasks.py
Removed server method
Prevents confusion for future developers
=> Removed server method from tasks.py

README.md
=> Edited readme by adding instructions to run Scrapi with the OSF

scrapi/harvesters/shareok.py
to only harvest sets where all the sets are in the approved list
=> Update shareok harvester

scrapi/base/helpers.py, scrapi/base/schemas.py, scrapi/tasks.py, tests/test_helpers.py
And update process normalized retry behavior
=> hotfix - Add DOIs as ObjectUris in standard OAI schema

scrapi/harvesters/dataone.py
**Purpose**
Put things stored in 'other properties' into proper places.
**Changes**
sorts urls, uris and contributor names into corrent catagory.
**Side Effects**
None that I know of.
=> modified dataone.py to fit schema.

scrapi/base/__init__.py, scrapi/base/helpers.py, scrapi/requests.py, tests/test_helpers.py
For really really big record caches!!
=> Update base OAI harvester to not gather records recursively

scrapi/requests.py, tests/test_requests.py
Add and mock a new sleep function that should hopefully fix periodic test failures
=> [hotfix] Mock new sleep function to fix periodic test failing

scrapi/base/__init__.py, scrapi/harvesters/shareok.py, tests/test_oai_harvester.py
Update SHAREOK harvester to harvest more specific sets, add verify to base OAI harvester to deal with off ssl certs in some cases
=> [hotfix] update SHAREOK, add verify property

scrapi/base/helpers.py
Fixes broken build on develop.
=> coerce the filter to a list for python3 compatibility

scrapi/processing/elasticsearch.py
=> Make ES backtransform any URL to the url field for the v1 API

tasks.py
Does this need to be there for the celery beat as well?
=> Add hostname to celery worker

README.md
- Splits the "Installing Cassandra and Elasticsearch" section into two sections
- Expands the "Working with the OSF" section to reflect the current process
=> Update readme for working with the OSF

scrapi/base/__init__.py, scrapi/base/helpers.py
Prevents mapper parsing exceptions in elasticsearch due to unparsed dates.
=> No more date errors

README.md
@erinspace's autooai tool is mentioned on the SHARE site, and I think it would be helpful to mention it here, too.  I may or may not have spent the better part of yesterday building the NOAA harvester manually because I didn't know about it.  ^_^  D'oh!
Cheers,
Fitz
=> mention autooai utility for writing harvesters

scrapi/linter/document.py
This should make sentry logs way more useful
=> add reprs for raw and normalized documents'

scrapi/harvesters/crossref.py
so that validation errors don't occur due to missing conditionally required components
=> conditionally create award object

tasks.py
=> Make start and end date parsing more sane

scrapi/requests.py
=> Make scrapi.requests implement requests.exceptions

README.md
=> Add correct harvester args to inv harvester README

scrapi/processing/elasticsearch.py
=> Make elasticsearch retry on connection error

scrapi/base/__init__.py, scrapi/base/helpers.py, scrapi/base/schemas.py, scrapi/harvesters/biomedcentral.py, scrapi/harvesters/clinicaltrials.py, scrapi/harvesters/crossref.py, scrapi/harvesters/dataone.py, scrapi/harvesters/dryad.py, scrapi/harvesters/figshare.py, scrapi/harvesters/harvarddataverse.py, scrapi/harvesters/osf.py, scrapi/harvesters/plos.py, scrapi/harvesters/pubmedcentral.py, scrapi/harvesters/smithsonian.py, scrapi/harvesters/springer.py, scrapi/registry.py, tasks.py, tests/test_json_harvester.py
I think the rest of the tests can be added incrementally, but the ability is there now.
=> Add support for doctests

scrapi/base/helpers.py, tests/test_helpers.py
Fixes [#SHARE-78] and [#SHARE-79]
=> Update URI processing

scrapi/base/__init__.py
Return rawdocs a list comprehension thanks @fabianvf
=> Make returning rawdocs in base harvest function better

.coveragerc, scrapi/harvesters/bhl.py, scrapi/harvesters/datacite.py, scrapi/settings/travis-dist.py, tests/vcr/crossref.yaml
Add funder information to the VCR for crossref.
Make tests for shareok run on travis
=> Fix up harvester testing a bit.

scrapi/harvesters/pubmedcentral.py
Account for latest incomplete URIs in identifier field (but still gather dois when available)
=> Update format uris pubmedcentral

api/api/settings/defaults.py
And remove the visual API renderer
=> Make json API default for GET route

scrapi/harvesters/csuohio.py
=> Change longname for csu

scrapi/base/helpers.py
fix my recover XML parsing error
=> check for encoding and recover if none

.travis.yml, scrapi/harvesters/push_api.py, scrapi/settings/local-dist.py
Update harvester params, normalize function
- Harvester query params now use updated "source" for push API
- Normalize now just grabs raw JSON coming back from API
=> Update push API harvester to match new json returned from API

tasks.py
`invoke one_test shortname` will now run a test on a single harvester
=> add test for one harvester

tasks.py
as referenced by #458 and #151 
this will clear all provider information in elasticsearch
=> add invoke clear to remove provider information from elasticsearch

scrapi/harvesters/springer.py
Updated springer harvester to ignore biomed central
Updated springer to log when a source is not biomed central or springer
=> [springer]

README.md
just wanted to add a note about the new invoke one_test method
=> added note about one_test

api/webview/serializers.py
Use django's json serializers to display raw and normalized as actual json
=> Use json serializers for raw and normalized

scrapi/harvesters/push_api.py, scrapi/processing/elasticsearch.py, tests/test_elasticsearch_processor.py
Push API harvester will check for "deleted" status and not normalize in that case
=> hotfix/Push API will not normalize documents marked with deleted status

README.md, tasks.py
A few small fixes encountered while installing
=> Installation fixes

scrapi/harvesters/nsfawards.py
=> Add code for the nsf awards harvester

scrapi/processing/storage.py
Reticketed from https://github.com/CenterForOpenScience/osf.io/pull/5264#issuecomment-211967591.
=> fix the local storage backend

scrapi/harvesters/elife.py
pull articles from elife's new repository
=> update elife repository
